if (!window.cards)
  window.cards = [
    {
      name: "Master Aqua",
      rarity: "Promo",
      cardType: "Champion",
      cp: 12,
      strength: 4,
      defense: 14,
      text: "When one of your “Blizzard” forms expires, draw a card.",
      specialType: "",
      specialText: "",
      attribute: "Magic",
      champTotal: 30,
      code: "aqua1",
    },
    {
      name: "Master Terra",
      rarity: "Promo",
      cardType: "Champion",
      cp: 10,
      strength: 6,
      defense: 14,
      text: "Terra’s attacks have Piercing.",
      specialType: "",
      specialText: "",
      attribute: "Power",
      champTotal: 30,
      code: "ven1",
    },
    {
      name: "Master Ventus",
      rarity: "Promo",
      cardType: "Champion",
      cp: 16,
      strength: 5,
      defense: 9,
      text: "Your “Aero” sleights have split. (Round down odd number values.)",
      specialType: "",
      specialText: "",
      attribute: "Speed",
      champTotal: 30,
      code: "tera1",
    },
    {
      name: "Sora, At Level 1 Again",
      rarity: "Promo",
      cardType: "Champion",
      cp: 12,
      strength: 4,
      defense: 14,
      text: "Your sleights that total 3 or less have piercing.",
      specialType: "",
      specialText: "",
      attribute: "Speed",
      champTotal: 30,
      code: "sora1",
    },
    {
      name: "Riku, Dark Scion",
      rarity: "Promo",
      cardType: "Champion",
      cp: 12,
      strength: 5,
      defense: 13,
      text: "“Dark” sleights you use that are not clashed deal 1 extra damage.",
      specialType: "",
      specialText: "",
      attribute: "Power",
      champTotal: 30,
      code: "riku1",
    },
    {
      name: "Kairi, Left Behind",
      rarity: "Promo",
      cardType: "Champion",
      cp: 14,
      strength: 3,
      defense: 13,
      text: "When you draw a card, if Kairi is in your back row, your active champion heals 1.",
      specialType: "",
      specialText: "",
      attribute: "Magic",
      champTotal: 30,
      code: "kai1",
    },
    {
      name: "Gravitas, Misery Incarnate",
      rarity: "Promo",
      cardType: "Champion",
      cp: 13,
      strength: 4,
      defense: 13,
      text: "At each player’s build phase, if their active champion has less than 13 defense, that champion takes 1 damage.",
      specialType: "",
      specialText: "",
      attribute: "Speed",
      champTotal: 30,
      code: "grav1",
    },
    {
      name: "Temporius, Eternity Crafter",
      rarity: "Promo",
      cardType: "Champion",
      cp: 17,
      strength: 3,
      defense: 10,
      text: "When Temporius deals damage with an attack, the attacked player discards a card.",
      specialType: "",
      specialText: "",
      attribute: "Magic",
      champTotal: 30,
      code: "temp1",
    },
    {
      name: "Artis, Remnant Artificer",
      rarity: "Promo",
      cardType: "Champion",
      cp: 8,
      strength: 6,
      defense: 16,
      text: "When you clash with a 0 cost card, Artis heals 2.",
      specialType: "",
      specialText: "",
      attribute: "Power",
      champTotal: 30,
      code: "art1",
    },
    {
      name: "Aqua, Headmaster",
      rarity: "Champion",
      cardType: "Champion",
      cp: 14,
      strength: 3,
      defense: 15,
      text: "When you draw a card, each of your backrow champions heal 1.",
      specialType: "",
      specialText: "",
      attribute: "Magic",
      champTotal: 32,
      code: "aqua2",
    },
    {
      name: "Salvare, Brash Conquerer",
      rarity: "Champion",
      cardType: "Champion",
      cp: 11,
      strength: 5,
      defense: 16,
      text: "When you play a card in your provision zone, Any sleight you use this turn gains piercing.",
      specialType: "",
      specialText: "",
      attribute: "Power",
      champTotal: 32,
      code: "salv1",
    },
    {
      name: "Fire",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText: "Sleights deal 1 extra damage.",
      attribute: "Magic",
      champTotal: 0,
      code: "fir",
    },
    {
      name: "Dark Fire",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText: "Your opponent discards a card.",
      attribute: "Magic",
      champTotal: 0,
      code: "daf",
    },
    {
      name: "Blizzard",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText: "Clash Sleights value increases by 1.",
      attribute: "Magic",
      champTotal: 0,
      code: "bli",
    },
    {
      name: "Dark Blizzard",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText: "increase the Clash value by 1.",
      attribute: "Magic",
      champTotal: 0,
      code: "dab",
    },
    {
      name: "Thunder",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Piercing",
      specialType: "Form",
      specialText: "Champion attacks deal 2 extra damage.",
      attribute: "Magic",
      champTotal: 0,
      code: "thu",
    },
    {
      name: "Dark Thunder",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText: "deal 3 damage to the opponent’s active champion.",
      attribute: "Magic",
      champTotal: 0,
      code: "dat",
    },
    {
      name: "Combo Plus",
      rarity: "UC Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Split",
      specialType: "Sleight",
      specialText: "Another card in the sleight gains split.",
      attribute: "Power",
      champTotal: 0,
      code: "com",
    },
    {
      name: "Wind Raid",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Piercing",
      specialType: "Clash",
      specialText: "Deal 2 damage to a champion on your opponent’s back row.",
      attribute: "Speed",
      champTotal: 0,
      code: "win",
    },
    {
      name: "Dark Dive",
      rarity: "Rare 6-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText:
        "When your active champion’s defense would hit 0, instead it becomes 1.",
      attribute: "Power",
      champTotal: 0,
      code: "dad",
    },
    {
      name: "Barrier",
      rarity: "UC Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Defending",
      specialType: "Form",
      specialText:
        "When your active champion’s defense would hit 0, instead it becomes 1.",
      attribute: "Magic",
      champTotal: 0,
      code: "bar",
    },
    {
      name: "Protect",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Defending",
      specialType: "Clash",
      specialText: "Your active champion heals 2.",
      attribute: "Speed",
      champTotal: 0,
      code: "pro",
    },
    {
      name: "Cure",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Healing",
      specialType: "Sleight",
      specialText: "A champion on your back row heals 2.",
      attribute: "Magic",
      champTotal: 0,
      code: "cur",
    },
    {
      name: "Cover Ally",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Healing",
      specialType: "Clash",
      specialText: "Your backrow champions each heal 2.",
      attribute: "Speed",
      champTotal: 0,
      code: "coa",
    },
    {
      name: "Sonic Blade",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText: "deal 2 damage to the opponent’s active champion.",
      attribute: "Speed",
      champTotal: 0,
      code: "son",
    },
    {
      name: "Earth",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText: "Increase Sleight value by 1.",
      attribute: "Magic",
      champTotal: 0,
      code: "ear",
    },
    {
      name: "Aero",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText: "reduce incoming damage by 2.",
      attribute: "Magic",
      champTotal: 0,
      code: "aer",
    },
    {
      name: "Triple Blizzaga",
      rarity: "Rare 6-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText: "deal 2 damage to each of the opponent’s backrow champions.",
      attribute: "Magic",
      champTotal: 0,
      code: "tpb",
    },
    {
      name: "Gravity",
      rarity: "UC Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText:
        "If the clash fails, your active champion takes 3 less damage.",
      attribute: "Magic",
      champTotal: 0,
      code: "gra",
    },
    {
      name: "Dodge Roll",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText:
        "On your next turn, you may rotate your Champions before damage.",
      attribute: "Speed",
      champTotal: 0,
      code: "dor",
    },
    {
      name: "Breach",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Piercing",
      specialType: "Sleight",
      specialText: "Another card in the sleight gains piercing.",
      attribute: "Power",
      champTotal: 0,
      code: "bre",
    },
    {
      name: "Charge",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Defending",
      specialType: "Clash",
      specialText: "Draw a card.",
      attribute: "Magic",
      champTotal: 0,
      code: "cha",
    },
    {
      name: "Cleanse",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText: "Shuffle your discard into your deck.",
      attribute: "Magic",
      champTotal: 0,
      code: "cle",
    },
    {
      name: "Guard",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Defending",
      specialType: "Clash",
      specialText: "Another card in the clash gains Defending.",
      attribute: "Power",
      champTotal: 0,
      code: "gua",
    },
    {
      name: "Strike Raid",
      rarity: "all 1-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Clash",
      specialText:
        "If the clash fails, deal 2 to the opponent’s active champion.",
      attribute: "Speed",
      champTotal: 0,
      code: "str",
    },
    {
      name: "Quick Hit",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Piercing",
      specialType: "Clash",
      specialText:
        "If this card was used in a Piercing Sleight with other commands, draw a card.",
      attribute: "Speed",
      champTotal: 0,
      code: "quh",
    },
    {
      name: "Dark Raid",
      rarity: "Rare 6+ Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "Split",
      specialType: "Clash",
      specialText:
        "If other “dark” cards are in the clash, remove the lowest value from the incoming sleight.",
      attribute: "Speed",
      champTotal: 0,
      code: "dar",
    },
    {
      name: "Warp",
      rarity: "Rare 6+ Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Form",
      specialText: "When you rotate your Champions, draw a card.",
      attribute: "Magic",
      champTotal: 0,
      code: "wrp",
    },
    {
      name: "Zantetsuken",
      rarity: "Rare 6-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText:
        "If every card in the sleight is a Power card and there are atleast 2 cards, the sleight gains Piercing.",
      attribute: "Power",
      champTotal: 0,
      code: "zan",
    },
    {
      name: "Gaia Belt",
      rarity: 0,
      cardType: "Item",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Item",
      specialText: "Power champions deal 2 more damage with attacks.",
      attribute: "",
      champTotal: 0,
      code: "",
    },
    {
      name: "Protect Chain",
      rarity: 0,
      cardType: "Item",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Item",
      specialText: "Your active champion takes 1 less damage.",
      attribute: "",
      champTotal: 0,
      code: "",
    },
    {
      name: "No Exp",
      rarity: 0,
      cardType: "Item",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Item",
      specialText:
        "Your champion’s strength is 1. Draw an additional card in your draw step.",
      attribute: "",
      champTotal: 0,
      code: "",
    },
    {
      name: "Morningstar",
      rarity: 0,
      cardType: "Item",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Item",
      specialText: "Whenever you draw a card, your active champion heals 1",
      attribute: "",
      champTotal: 0,
      code: "",
    },
    {
      name: "Earth Impact",
      rarity: "UC Odd",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText:
        "If another “Earth” command is in the sleight, increase Sleight value by 1.",
      attribute: "Power",
      champTotal: 0,
      code: "eai",
    },
    {
      name: "Ars Solem",
      rarity: "Rare 6-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText:
        "If another “Ars” command is in the sleight, the sleight gains Piercing.",
      attribute: "Power",
      champTotal: 0,
      code: "ars",
    },
    {
      name: "Ars Arcanum",
      rarity: "Rare 6+ Even",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText:
        "If another “Ars” command is in the sleight, the sleight gains Split.",
      attribute: "Speed",
      champTotal: 0,
      code: "ara",
    },
    {
      name: "Sacrifice",
      rarity: "Rare 6-9",
      cardType: "Command",
      cp: "",
      strength: "",
      defense: "",
      text: "",
      specialType: "Sleight",
      specialText: "Both active champions take 5 damage.",
      attribute: "Power",
      champTotal: 0,
      code: "sac",
    },
  ];
